coin: Install local Homebrew formulas explicitly as formula
Otherwise we end up with scary warnings like:

Error: Failed to load cask: ./coin/provisioning/common/macos/libiodbc.rb
Cask 'libiodbc' is unreadable: wrong constant name #<Class:0x00007fb4f589d2d8>
Warning: Treating ./coin/provisioning/common/macos/libiodbc.rb as a formula.

Change-Id: Ief1b78c70367c740ce7eeca9110c3cf41372f53a
Reviewed-by: Heikki Halmet <heikki.halmet@qt.io>
(cherry picked from commit d3867057b95364b5e88a761f3c38e5ac96c6c2f5)
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>