Revert "Provisioning: Add Windows 11 on ARM as non-blocking in CI"
This reverts commit 72f11e0952701b3722d53292e748e1895703bcab.

Reason for revert: WoA is not going be included in 6.7 and WoA target is blocking dd08ded0fc20f5fce10bf287d4d22ae026226717, -51 template will not work with the proxy enabled and -53 template brings error C2672 with its updated MSVC in 6.7 qtbase.

Task-number: QTQAINFRA-6111
Change-Id: I13fde01aba392b173db178bff6893b71c20ae98a
Reviewed-by: Jani Heikkinen <jani.heikkinen@qt.io>