CMake: Update provisioned CMake to version 3.24.2
Needed to fix iOS Xcode generator builds when using Xcode 14.
Otherwise compiler identification fails due to a code-signing error.
We hit it in our iOS MinimalStaticTests configuration.

 error: Cannot code sign because the target does not have an
        Info.plist file and one is not being generated
        automatically.
         (in target 'CompilerIdCXX' from project
         'CompilerIdCXX')

See https://gitlab.kitware.com/cmake/cmake/-/issues/23719

Amends eee152ca704d501189905122a904255f581b3256

Fixes: QTQAINFRA-5044
Change-Id: Idabd78e6e28816a8fc4dd7e627de82f2c622c54e
Reviewed-by: Alexey Edelev <alexey.edelev@qt.io>
(cherry picked from commit 6943f28b171f0d3a1d39bde55732948a23391219)
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>